services:
  glue_pyspark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glue_pyspark
    ports:
      - "4040:4040"       # Spark UI
      - "18080:18080"     # History server (if configured)
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
      AWS_REGION: "${AWS_REGION}"
    volumes:
      - ${PWD}:/home/glue_user/workspace
    stdin_open: true
    tty: true
    networks:
      - default_network
    restart: always

networks:
  default_network:
    driver: bridge
